server:
  port: 8080
#  servlet:
#    context-path: /api

spring:
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

auth:
  jwt:
    secret: ${jwt_secret}

aws:
  region: ${AWS_REGION}
  bucket-name: tweederstorage
  base-url: https://tweederstorage.s3.eu-north-1.amazonaws.com/
