server:
  port: 8081
#  servlet:
#    context-path: /api

spring:
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

auth:
  jwt:
    secret: ${jwt_secret}

aws:
  region: ${AWS_REGION}
  bucket-name: tweederstorage
