server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

auth:
  jwt:
    secret: ${jwt_secret}
