server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

auth:
  jwt:
    secret: ${jwt_secret}
